services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    volumes:
      - outputs:/app/outputs # Mount the outputs volume

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # for management UI

volumes:
  outputs: # Define the outputs volume